### ISSUE TITLE
consent manager and rewarded video signals causes crashes

### ISSUE THREAD

**Issue by yamuru** [PoqXert/godot-appodeal-android-plugin#9]
Godot: 3.4.4 stable

Started researching appodeal a while ago and today I have found this repo
I didn't find anything about something called consentManager library here (I don't know what is it yet), but appodeal recommends me to use it. What can I do?

About the problem:
When listening to "rewarded_video_closed"  signal my game crashes with this error:
```
java.lang.IllegalArgumentException: Invalid type for argument #1. Should be of type java.lang.String
at org.godotengine.godot.plugin.GodotPlugin.emitSignal(GodotPlugin.java:376)
at org.godotengine.godot.plugin.GodotPlugin.emitSignal(GodotPlugin.java:343)
at ru.poqxert.godotappodeal.GodotAppodeal.access$1700(GodotAppodeal.java:35)
at ru.poqxert.godotappodeal.GodotAppodeal$3.onRewardedVideoFinished(GodotAppodeal.java:230)
at com.appodeal.ads.q1.b(Unknown Source)
at com.appodeal.ads.q1.b(Unknown Source)
at com.appodeal.ads.n$j.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

"rewarded_video_finished" causes a crash too. Interstitial ads work fine
The crash happens at the moment when I close the rewarded ad

This is my appodeal autoload:
```
extends Node

var _appodeal

enum AdType {
	INTERSTITIAL = 1,
	BANNER = 2,
	NATIVE = 4,
	REWARDED_VIDEO = 8,
	NON_SKIPPABLE_VIDEO = 16,
}

enum ShowStyle {
	INTERSTITIAL = 1,
	BANNER_TOP = 2,
	BANNER_BOTTOM = 4,
	REWARDED_VIDEO = 8,
	NON_SKIPPABLE_VIDEO = 16,
}

func _ready():
	var is_testing = !_glob_Variables.ARE_ADS_REAL
	
	if Engine.has_singleton("GodotAppodeal"):
		_appodeal = Engine.get_singleton("GodotAppodeal")
		
	
	
	if _appodeal:
		_appodeal.initialize(
			"sensitive",
			AdType.BANNER | AdType.INTERSTITIAL | AdType.NON_SKIPPABLE_VIDEO | AdType.REWARDED_VIDEO, 
			!_glob_Progress.first_launch
		)
		_appodeal.setTestingEnabled(is_testing)

func change_consent(consent):
	if _appodeal:
		_appodeal.updateConsent(consent)

func cache_ad(ad_type):
	if _appodeal:
		_appodeal.cacheAd(ad_type)

func show_ad(show_style):
	if _appodeal:
		_appodeal.showAd(show_style)
```

This is how I use it:

```
func _ready():
        ...
	...
	if _glob_Appodeal._appodeal:
		_glob_Appodeal._appodeal.connect("rewarded_video_closed", self, "rewarded_video_closed")
		_glob_Appodeal._appodeal.connect("interstitial_closed", self, "interstitial_closed")

...

func _on_MenuButton_pressed():
	_glob_Appodeal.show_ad(_glob_Appodeal.ShowStyle.INTERSTITIAL)

func _on_AdButton_pressed():
	_glob_Appodeal.show_ad(_glob_Appodeal.ShowStyle.REWARDED_VIDEO)

...

func rewarded_video_closed(finished):
	if finished:
		get_tree().paused = false
		_glob_Progress.dollars += _glob_Waves.current_wave * dollars_for_wave
		_glob_Progress.save_progress()
		
		_glob_Waves.reset_waves()
		_glob_Scenes.goto_scene(_glob_Scenes.Scenes_dict.Menu)
```

My GodotAppodeal.gdap (If I use the SDK versions from README of this repo, I get errors telling me that it's impossible to download those SDKs):
```
[config]

name="GodotAppodeal"
binary_type="local"
binary="GodotAppodeal.1.0.1.release.aar"

[dependencies]

remote=["com.appodeal.ads.sdk:core:2.11.1",
"com.appodeal.ads.sdk.networks:appodeal:2.11.1.3",
"com.appodeal.ads.sdk.networks:mraid:2.11.1.5",
"com.appodeal.ads.sdk.networks:nast:2.11.1.3",
"com.appodeal.ads.sdk.networks:vast:2.11.1.5",
"com.appodeal.ads.sdk.networks:adcolony:2.11.1.22",
"com.appodeal.ads.sdk.networks:applovin:2.11.1.24",
"com.appodeal.ads.sdk.networks:bidmachine:2.11.1.21",
"com.appodeal.ads.sdk.networks:ironsource:2.11.1.21",
"com.appodeal.ads.sdk.networks:my_target:2.11.1.22",
"com.appodeal.ads.sdk.networks:ogury:2.11.1.12",
"com.appodeal.ads.sdk.networks:unity_ads:2.11.1.17",
"com.appodeal.ads.sdk.networks:vungle:2.11.1.14"]
custom_maven_repos=["https://artifactory.appodeal.com/appodeal"]
```

I really have no idea what should I do :/ Any thoughts?

Have a good day! :)

**Comment by PoqXert** [comment]
@yamuru you can use [Consent Manager Plugin](https://github.com/PoqXert/gaconsentmanager-android-plugin).
GodotAppodeal 1.0.1 not compatibility with Appodeal 2.11.1, use [v1.1.0](https://github.com/PoqXert/godot-appodeal-android-plugin/releases/tag/1.1.0)
